import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body>
            <header style={{ border: "1px solid" }}>This header is shared amongst all pages</header>
            {children}
            <footer style={{ border: "1px solid" }}>This footer is shared amongst all pages</footer>
         </body>
      </html>
   );
}
